# Generated by Django 4.0.6 on 2022-07-31 16:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliate_id', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliate_cid', models.CharField(blank=True, max_length=255, null=True)),
                ('gclid', models.CharField(blank=True, max_length=255, null=True)),
                ('gacid', models.CharField(blank=True, max_length=255, null=True)),
                ('msclkid', models.CharField(blank=True, max_length=255, null=True)),
                ('users_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True, blank=True)),
            ],
        ),
    ]
