# Generated by Django 4.0.6 on 2022-08-03 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
